"""contenido curricular MCER: modules ricos + tutor_policy en cefr_levels

Revision ID: 04e347401fbb
Revises: 9c7d07c6245b
Create Date: 2026-09-02 21:03:37.656815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04e347401fbb'
down_revision: Union[str, None] = '9c7d07c6245b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default en las columnas NOT NULL (a mano; autogenerate no lo
    # infiere): la tabla está vacía hoy, pero sin default esta migración
    # rompería en cualquier entorno donde ya existieran filas.
    op.add_column(
        'cefr_levels',
        sa.Column('tutor_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
    )
    op.add_column('modules', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('modules', sa.Column('title_es', sa.String(length=255), nullable=True))
    op.add_column(
        'modules', sa.Column('descriptors', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}')
    )
    op.add_column(
        'modules', sa.Column('recycles', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}')
    )
    op.add_column(
        'modules',
        sa.Column('communicative_objectives', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    op.add_column(
        'modules', sa.Column('grammar', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}')
    )
    op.add_column(
        'modules', sa.Column('lexis', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}')
    )
    op.add_column(
        'modules',
        sa.Column('pronunciation', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
    )
    op.add_column(
        'modules',
        sa.Column('l1_interference', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    )
    op.add_column(
        'modules', sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]')
    )
    op.add_column(
        'modules',
        sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
    )
    op.add_column(
        'modules',
        sa.Column('tutor_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
    )
    op.create_index(op.f('ix_modules_code'), 'modules', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modules_code'), table_name='modules')
    op.drop_column('modules', 'tutor_config')
    op.drop_column('modules', 'assessment')
    op.drop_column('modules', 'tasks')
    op.drop_column('modules', 'l1_interference')
    op.drop_column('modules', 'pronunciation')
    op.drop_column('modules', 'lexis')
    op.drop_column('modules', 'grammar')
    op.drop_column('modules', 'communicative_objectives')
    op.drop_column('modules', 'recycles')
    op.drop_column('modules', 'descriptors')
    op.drop_column('modules', 'title_es')
    op.drop_column('modules', 'code')
    op.drop_column('cefr_levels', 'tutor_policy')
    # ### end Alembic commands ###
