"""users.access_exempt: cuentas existentes conservan el acceso

Revision ID: 1b64c11b9cb4
Revises: 57ebceaa4640
Create Date: 2026-09-21 22:16:56.095436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b64c11b9cb4'
down_revision: Union[str, None] = '57ebceaa4640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_exempt', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###

    # Las cuentas que YA existían conservan el acceso gratis que tenían: el
    # cobro solo aplica a las que se registren a partir de ahora (decisión
    # de negocio del 21/09/2026). Las nuevas nacen con el default: false.
    op.execute("UPDATE users SET access_exempt = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_exempt')
    # ### end Alembic commands ###
