"""conversation_sessions.module_id: atar una sesion de chat a un modulo

Revision ID: 2a99a92acfc3
Revises: a1be33ea9ef4
Create Date: 2026-09-02 21:29:15.358740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a99a92acfc3'
down_revision: Union[str, None] = 'a1be33ea9ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nombre explícito en la FK (autogenerate propuso None): sin nombre,
    # el downgrade no tiene cómo referenciarla para borrarla.
    op.add_column('conversation_sessions', sa.Column('module_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_conversation_sessions_module_id', 'conversation_sessions', 'modules', ['module_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversation_sessions_module_id', 'conversation_sessions', type_='foreignkey')
    op.drop_column('conversation_sessions', 'module_id')
    # ### end Alembic commands ###
