"""lesson: script y audio narrado (Ollama + Piper TTS)

Revision ID: 35300c409adb
Revises: ea31e2d04f00
Create Date: 2026-08-31 23:20:18.563155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35300c409adb'
down_revision: Union[str, None] = 'ea31e2d04f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('script', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('audio_url', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('audio_duration_seconds', sa.Float(), nullable=True))
    op.add_column('lessons', sa.Column('audio_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'audio_generated_at')
    op.drop_column('lessons', 'audio_duration_seconds')
    op.drop_column('lessons', 'audio_url')
    op.drop_column('lessons', 'script')
    # ### end Alembic commands ###
