"""CEFRLevel.exit_gate: version ejecutable del gate de salida de nivel

Revision ID: 4d43f564677c
Revises: 2a99a92acfc3
Create Date: 2026-09-02 21:37:48.860741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d43f564677c'
down_revision: Union[str, None] = '2a99a92acfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cefr_levels', sa.Column('exit_gate', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cefr_levels', 'exit_gate')
    # ### end Alembic commands ###
