"""biblioteca: cursos flash y su progreso

Revision ID: 705e300a0118
Revises: 8a3247e25a8f
Create Date: 2026-09-16 23:54:11.340038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '705e300a0118'
down_revision: Union[str, None] = '8a3247e25a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flash_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_es', sa.String(length=255), nullable=False),
    sa.Column('description_es', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('recommended_level', sa.String(length=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('communicative_objectives', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('key_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scenarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tutor_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('l1_interference', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flash_courses_slug'), 'flash_courses', ['slug'], unique=True)
    op.create_table('flash_course_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('completed_scenarios', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['flash_courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_flash_course_progress_user_course')
    )
    op.create_index(op.f('ix_flash_course_progress_user_id'), 'flash_course_progress', ['user_id'], unique=False)
    op.add_column('conversation_sessions', sa.Column('flash_course_id', sa.UUID(), nullable=True))
    # Con nombre explícito: autogenerate la deja sin nombre (None), y así
    # el downgrade no tiene forma de referirse a ella para borrarla.
    op.create_foreign_key(
        'fk_conversation_sessions_flash_course_id', 'conversation_sessions', 'flash_courses',
        ['flash_course_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversation_sessions_flash_course_id', 'conversation_sessions', type_='foreignkey')
    op.drop_column('conversation_sessions', 'flash_course_id')
    op.drop_index(op.f('ix_flash_course_progress_user_id'), table_name='flash_course_progress')
    op.drop_table('flash_course_progress')
    op.drop_index(op.f('ix_flash_courses_slug'), table_name='flash_courses')
    op.drop_table('flash_courses')
    # ### end Alembic commands ###
