"""juego de completar oraciones: progreso del alumno

Revision ID: 70e4b469a254
Revises: 705e300a0118
Create Date: 2026-09-17 13:25:38.076228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70e4b469a254'
down_revision: Union[str, None] = '705e300a0118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_game_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_progress', sa.Integer(), nullable=False),
    sa.Column('total_answered', sa.Integer(), nullable=False),
    sa.Column('total_correct', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('pending_item_id', sa.String(length=20), nullable=True),
    sa.Column('recent_item_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence_game_progress')
    # ### end Alembic commands ###
