"""rol de usuario y tabla user_events para analítica

Revision ID: 71873999414c
Revises: 94afab531e9a
Create Date: 2026-08-31 22:36:32.671204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71873999414c'
down_revision: Union[str, None] = '94afab531e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_events_event_type'), 'user_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    op.create_index('ix_user_events_user_type_time', 'user_events', ['user_id', 'event_type', 'created_at'], unique=False)
    # server_default a propósito (no solo el default de Python en el
    # modelo): sin esto, el ADD COLUMN ... NOT NULL falla en cuanto la
    # tabla "users" tenga una sola fila ya existente — Postgres necesita
    # un valor para rellenar las filas que ya están ahí.
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='student'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index('ix_user_events_user_type_time', table_name='user_events')
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_type'), table_name='user_events')
    op.drop_table('user_events')
    # ### end Alembic commands ###
