"""monitoreo tecnico: llm_calls, request_logs, client_errors

Revision ID: 83ee570cc72d
Revises: 70e4b469a254
Create Date: 2026-09-18 17:51:07.419113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ee570cc72d'
down_revision: Union[str, None] = '70e4b469a254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_errors_created_at', 'client_errors', ['created_at'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('queue_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('input_chars', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(length=30), nullable=True),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_calls_created_at', 'llm_calls', ['created_at'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_logs_created_at', 'request_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_logs_created_at', table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index('ix_llm_calls_created_at', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_client_errors_created_at', table_name='client_errors')
    op.drop_table('client_errors')
    # ### end Alembic commands ###
