"""preferencia de notificaciones del alumno

Revision ID: 8a3247e25a8f
Revises: 93654fcb02bf
Create Date: 2026-09-09 15:20:09.978461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3247e25a8f'
down_revision: Union[str, None] = '93654fcb02bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default NO es opcional aquí: añadir una columna NOT NULL sin
    # valor por defecto falla en cuanto la tabla tiene una sola fila, y
    # `users` siempre las tiene en cualquier entorno que no sea nuevo.
    # Autogenerate no lo pone porque el default vive en Python
    # (mapped_column(default=True)), que solo se aplica a filas NUEVAS.
    op.add_column(
        'users',
        sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    # ### end Alembic commands ###
