"""script_segments: linea de tiempo del guion narrado

Revision ID: 93654fcb02bf
Revises: 0129bb83280f
Create Date: 2026-09-09 13:31:35.798480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93654fcb02bf'
down_revision: Union[str, None] = '0129bb83280f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('script_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'script_segments')
    # ### end Alembic commands ###
