"""ajustar dimension de summary_embedding a 768 (nomic-embed-text)

Revision ID: 94afab531e9a
Revises: d17c7d02cd77
Create Date: 2026-08-31 19:18:20.066839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # ver nota en la migración inicial: autogenerate no lo añade solo


# revision identifiers, used by Alembic.
revision: str = '94afab531e9a'
down_revision: Union[str, None] = 'd17c7d02cd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_sessions', 'summary_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_sessions', 'summary_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
