"""horas de certificacion: CEFRLevel.target_hours, Module.estimated_hours

Revision ID: 9c7d07c6245b
Revises: 35300c409adb
Create Date: 2026-08-31 23:45:55.641683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7d07c6245b'
down_revision: Union[str, None] = '35300c409adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default en las tres a propósito: cefr_levels y modules ya
    # tienen filas (los 6 niveles y el módulo de ejemplo sembrados
    # antes) — mismo motivo de siempre, ver users.role o exercises.stage.
    op.add_column('cefr_levels', sa.Column('target_hours_min', sa.Integer(), nullable=False, server_default='80'))
    op.add_column('cefr_levels', sa.Column('target_hours_max', sa.Integer(), nullable=False, server_default='150'))
    op.add_column('modules', sa.Column('estimated_hours', sa.Float(), nullable=False, server_default='10.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'estimated_hours')
    op.drop_column('cefr_levels', 'target_hours_max')
    op.drop_column('cefr_levels', 'target_hours_min')
    # ### end Alembic commands ###
