"""catalogo de descriptores MCER + evidencia de dominio acumulada

Revision ID: a1be33ea9ef4
Revises: 04e347401fbb
Create Date: 2026-09-02 21:14:39.496053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1be33ea9ef4'
down_revision: Union[str, None] = '04e347401fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descriptors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('skill', sa.String(length=30), nullable=False),
    sa.Column('statement_en', sa.Text(), nullable=False),
    sa.Column('statement_es', sa.Text(), nullable=False),
    sa.Column('modules', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('l1_specific', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['cefr_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descriptors_code'), 'descriptors', ['code'], unique=True)
    op.create_table('descriptor_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('descriptor_code', sa.String(length=20), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=False),
    sa.Column('session_key', sa.String(length=255), nullable=False),
    sa.Column('scaffolded', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descriptor_evidence_descriptor_code'), 'descriptor_evidence', ['descriptor_code'], unique=False)
    op.create_index(op.f('ix_descriptor_evidence_user_id'), 'descriptor_evidence', ['user_id'], unique=False)
    # server_default a mano: estas dos columnas se añaden sobre tablas que
    # podrían ya tener filas (a diferencia de descriptors/descriptor_evidence,
    # que son tablas nuevas) — sin default, ALTER TABLE ... NOT NULL rompería.
    op.add_column(
        'cefr_levels',
        sa.Column('mastery_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
    )
    op.add_column(
        'exercises',
        sa.Column('descriptor_codes', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'descriptor_codes')
    op.drop_column('cefr_levels', 'mastery_rule')
    op.drop_index(op.f('ix_descriptor_evidence_user_id'), table_name='descriptor_evidence')
    op.drop_index(op.f('ix_descriptor_evidence_descriptor_code'), table_name='descriptor_evidence')
    op.drop_table('descriptor_evidence')
    op.drop_index(op.f('ix_descriptors_code'), table_name='descriptors')
    op.drop_table('descriptors')
    # ### end Alembic commands ###
