"""exercise.stage: practica vs examen

Revision ID: ea31e2d04f00
Revises: 3d5692ef75cc
Create Date: 2026-08-31 23:12:48.601171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea31e2d04f00'
down_revision: Union[str, None] = '3d5692ef75cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default a propósito (igual que con users.role): la tabla
    # "exercises" ya tiene filas, y un ADD COLUMN ... NOT NULL sin default
    # falla en cuanto hay una sola fila existente. "practice" es el valor
    # más seguro para contenido ya creado: no empieza a contar de golpe
    # para el mastery_score de nadie sin que un admin lo marque "exam" a propósito.
    op.add_column('exercises', sa.Column('stage', sa.String(length=10), nullable=False, server_default='practice'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'stage')
    # ### end Alembic commands ###
